workspace:
  path: src

pipeline:
  build:
    image: webhippie/ruby:latest
    commands:
      - bundle install
      - jekyll build -V

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: tboerger/webhippie
    tags: [ '${TAG}' ]
    when:
      event: tag
      branch: refs/tags/*

  docker:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: tboerger/webhippie
    tags: [ 'latest' ]
    when:
      event: push
      branch: master

  gitter:
    image: plugins/gitter
    secrets: [ gitter_webhook ]
