name: Webhippie
description: Software Entwicklung und Consulting

author: Webhippie Team
author_email: mail@webhippie.de

paginate: 5
pygments: true
markdown: rdiscount
permalink: /:year/:month/:day/:title/
