name: Webhippie
description: Software Entwicklung und Consulting

author: Webhippie Team
author_email: mail@webhippie.de

url: http://webhippie.de
permalink: /blog/:title

assets:
  cache_assets: true
  compress:
    css: sass
    js:  uglifier

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
