name : Webhippie United
brand : Webhippie
description : Software- und Web-Entwicklung
keyword:  
url : http://webhippie.de
email : mail@webhippie.com
author: Webhippie Team
markdown: kramdown
pygments: true
permalink: /:title
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
