name: Webhippie
description: Software Entwicklung und Consulting

author: Webhippie Team
author_email: mail@webhippie.de

url: http://webhippie.de

paginate: 5
pygments: true
markdown: rdiscount
permalink: /:year/:month/:day/:title/

# defaults
sass:
  syntax: scss        # scss|sass
  style:  compressed  # nested|expanded|compact|compressed
